name: Kotlin
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: kotlinc BubbleSort.kt -include-runtime -d BubbleSort.jar
      - run: java -jar BubbleSort.jar
